### ISSUE TITLE
Update Profile informations

### ISSUE THREAD

**Issue by MedAliG** [Tabwire/ApexTab-API#10]
Greetings, Thanks for the "API" and all , but the problem is the profile informations does not get updated only if you visit the website.
Is it possible to get the API to update it self if we request a specific user ?
Thanks in advance :D

**Comment by AustinLeath** [comment]
We are looking into this, expect it to work the way it does for a few weeks, we are working on a lot of things right now. I will pass this suggestion onto the guy that handles this API.

**Comment by MedAliG** [comment]
Okeh .thanks for the help !
