### ISSUE TITLE
Adding a new user to apextab database

### ISSUE THREAD

**Issue by Dmurph24** [Tabwire/ApexTab-API#11]
It's still unclear to me if this API only returns specific users that are in ApexTab, or this includes all players that search their name. Some usernames I search return not found, and other random username are found. Is there any documentation on what this API has and how to add new users if this is possible?

**Comment by openmilk** [comment]
Users are cached into thew system to my belief, 
anyone the system has not cached require waiting as few mins on my end

Atleast to my experience
