### ISSUE TITLE
Return of data with 0 value

### ISSUE THREAD

**Issue by seila16** [Tabwire/ApexTab-API#13]
First congratulations for your job in this API, well i have a problem with the response of the URL, i was doing tests with my gamertag and with my friends gamertag of Xbox Live Brazil, the return of the data is ever 0 value, look at the example

The request: https://apextab.com/api/player.php?aid=08eee372bc9c9867568b03fb152dfae0

Result:
"playerfound": true,
    "aid": "08eee372bc9c9867568b03fb152dfae0",
    "name": "Felipe Loki",
    "platform": "XBL",
    "skillratio": 0,
    "visits": "0",
    "avatar": "https://apextab.com/cache/fcbf628519c47e8de53fc46379258e43.png",
    "legend": "Unknown",
    "level": "0",
    "kills": "322",
    "headshots": "0",
    "matches": "0",
    "damage": "0",
    "lastdata": null,
    "kills_Bloodhound": "0",
    "kills_Gibraltar": "0",
    "kills_Lifeline": "0",
    "kills_Pathfinder": "0",
    "kills_Wraith": "322",
    "kills_Bangalore": "0",
    "kills_Caustic": "0",
    "kills_Mirage": "0",
    "headshots_Bloodhound": "0",
    "headshots_Gibraltar": "0",
    "headshots_Lifeline": "0",
    "headshots_Pathfinder": "0",
    "headshots_Wraith": "0",
    "headshots_Bangalore": "0",
    "headshots_Caustic": "0",
    "headshots_Mirage": "0",
    "matches_Bloodhound": "0",
    "matches_Gibraltar": "0",
    "matches_Lifeline": "0",
    "matches_Pathfinder": "0",
    "matches_Wraith": "0",
    "matches_Bangalore": "0",
    "matches_Caustic": "0",
    "matches_Mirage": "0",
    "damage_Bloodhound": "0",
    "damage_Gibraltar": "0",
    "damage_Lifeline": "0",
    "damage_Pathfinder": "0",
    "damage_Wraith": "0",
    "damage_Bangalore": "0",
    "damage_Caustic": "0",
    "damage_Mirage": "0",
    "globalrank": "384256",
    "utime": "1552660305",
    "daily_stats": null

Can you help me?

**Comment by openmilk** [comment]
Anything with zero either means they are at zero, or the api cant get the value
This and alot of other api's can only get the stats on your player cards

**Comment by seila16** [comment]
But the api get the data of the last legend i was play or get the data of all legends player card? Because i have the data "kills" with my pathfinder but the api return 0 kills with the pathfinder, but if my last legend is the pathfinder the api return the number of kills with pathfinder correctly.
