### ISSUE TITLE
API not updating

### ISSUE THREAD

**Issue by ajay340** [Tabwire/ApexTab-API#15]
The API does not seem to update when you send a get request unless you search the user on apextab.com.

**Comment by Mom0aut** [comment]
> The API does not seem to update when you send a get request unless you search the user on apextab.com.

Thats some problem, is there any way to update it with the Service-Call?

**Comment by dpedoneze** [comment]
Hi @Tabwire, is this the expected behavior?

**Comment by Tabwire** [comment]
No, it should work in anyway, the API does exactly the same call that our website do.

**Comment by dpedoneze** [comment]
Maybe there's some cache problem because it ins't updating when we call the api (we have to search @ apextab and then the api response is updated).

---

API get result @ 21:54 UTC
```json
{
  "results": [
    {
      "aid": "3983fe400d9872673fb66f7a6c27f67e",
      "name": "XuaZ",
      "platform": "pc",
      "avatar": "https://apextab.com/cache/b34a6a008e620d36d365300b52bd7576.png",
      "legend": "Lifeline",
      "level": "64",
      "kills": "396"
    }
  ],
  "totalresults": 1
}
```

```json
{
  "playerfound": true,
  "aid": "3983fe400d9872673fb66f7a6c27f67e",
  "name": "XuaZ",
  "platform": "PC",
  "skillratio": 0,
  "visits": "16",
  "avatar": "https://apextab.com/cache/b34a6a008e620d36d365300b52bd7576.png",
  "legend": "Lifeline",
  "level": "64",
  "kills": "396",
  "headshots": "558",
  "hstokills": "0",
  "matches": "0",
  "damage": "133205",
  "lastdata": null,
  "kills_Bloodhound": "106",
  "kills_Gibraltar": "0",
  "kills_Lifeline": "7",
  "kills_Pathfinder": "4",
  "kills_Wraith": "107",
  "kills_Bangalore": "2",
  "kills_Caustic": "0",
  "kills_Mirage": "155",
  "headshots_Bloodhound": "175",
  "headshots_Gibraltar": "0",
  "headshots_Lifeline": "0",
  "headshots_Pathfinder": "0",
  "headshots_Wraith": "173",
  "headshots_Bangalore": "0",
  "headshots_Caustic": "0",
  "headshots_Mirage": "210",
  "matches_Bloodhound": "0",
  "matches_Gibraltar": "0",
  "matches_Lifeline": "0",
  "matches_Pathfinder": "0",
  "matches_Wraith": "0",
  "matches_Bangalore": "0",
  "matches_Caustic": "0",
  "matches_Mirage": "0",
  "damage_Bloodhound": "41113",
  "damage_Gibraltar": "0",
  "damage_Lifeline": "0",
  "damage_Pathfinder": "0",
  "damage_Wraith": "38717",
  "damage_Bangalore": "0",
  "damage_Caustic": "0",
  "damage_Mirage": "53375",
  "globalrank": "77539",
  "utime": "1553961655",
  "kills_Octane": "15",
  "headshots_Octane": "0",
  "matches_Octane": "0",
  "damage_Octane": "0",
  "daily_stats": {
    "1551657600": {
      "kills": 24,
      "headshots": 76,
      "matches": 0,
      "damage": 18405
    },
    "1551744000": {
      "kills": 18,
      "headshots": 17,
      "matches": 0,
      "damage": 4278
    },
    "1551830400": {
      "kills": 2,
      "headshots": 7,
      "matches": 0,
      "damage": 1752
    },
    "1551916800": {
      "kills": 30,
      "headshots": 31,
      "matches": 0,
      "damage": 11137
    },
    "1552003200": {
      "kills": 36,
      "headshots": 37,
      "matches": 0,
      "damage": 8625
    },
    "1552780800": {
      "kills": 75,
      "headshots": 197,
      "matches": 0,
      "damage": 42352
    },
    "1552867200": {
      "kills": 54,
      "headshots": 71,
      "matches": 0,
      "damage": 20745
    },
    "1553644800": {
      "kills": 15,
      "headshots": 46,
      "matches": 0,
      "damage": 6721
    },
    "1553990400": {
      "kills": 15,
      "headshots": 0,
      "matches": 0,
      "damage": 0
    }
  }
}
```

Then, i've searched @ apextab and sent another get to the api

```json
{
  "results": [
    {
      "aid": "3983fe400d9872673fb66f7a6c27f67e",
      "name": "XuaZ",
      "platform": "pc",
      "avatar": "https://apextab.com/cache/b34a6a008e620d36d365300b52bd7576.png",
      "legend": "Octane",
      "level": "66",
      "kills": "414"
    }
  ],
  "totalresults": 1
}
```

```json
{
  "playerfound": true,
  "aid": "3983fe400d9872673fb66f7a6c27f67e",
  "name": "XuaZ",
  "platform": "PC",
  "skillratio": 0,
  "visits": "17",
  "avatar": "https://apextab.com/cache/b34a6a008e620d36d365300b52bd7576.png",
  "legend": "Octane",
  "level": "66",
  "kills": "414",
  "headshots": "615",
  "hstokills": "0",
  "matches": "0",
  "damage": "144947",
  "lastdata": null,
  "kills_Bloodhound": "106",
  "kills_Gibraltar": "0",
  "kills_Lifeline": "7",
  "kills_Pathfinder": "4",
  "kills_Wraith": "107",
  "kills_Bangalore": "2",
  "kills_Caustic": "0",
  "kills_Mirage": "155",
  "headshots_Bloodhound": "175",
  "headshots_Gibraltar": "0",
  "headshots_Lifeline": "0",
  "headshots_Pathfinder": "0",
  "headshots_Wraith": "173",
  "headshots_Bangalore": "0",
  "headshots_Caustic": "0",
  "headshots_Mirage": "210",
  "matches_Bloodhound": "0",
  "matches_Gibraltar": "0",
  "matches_Lifeline": "0",
  "matches_Pathfinder": "0",
  "matches_Wraith": "0",
  "matches_Bangalore": "0",
  "matches_Caustic": "0",
  "matches_Mirage": "0",
  "damage_Bloodhound": "41113",
  "damage_Gibraltar": "0",
  "damage_Lifeline": "0",
  "damage_Pathfinder": "0",
  "damage_Wraith": "38717",
  "damage_Bangalore": "0",
  "damage_Caustic": "0",
  "damage_Mirage": "53375",
  "globalrank": "77537",
  "utime": "1553982926",
  "kills_Octane": "33",
  "headshots_Octane": "57",
  "matches_Octane": "0",
  "damage_Octane": "11742",
  "daily_stats": {
    "1551657600": {
      "kills": 24,
      "headshots": 76,
      "matches": 0,
      "damage": 18405
    },
    "1551744000": {
      "kills": 18,
      "headshots": 17,
      "matches": 0,
      "damage": 4278
    },
    "1551830400": {
      "kills": 2,
      "headshots": 7,
      "matches": 0,
      "damage": 1752
    },
    "1551916800": {
      "kills": 30,
      "headshots": 31,
      "matches": 0,
      "damage": 11137
    },
    "1552003200": {
      "kills": 36,
      "headshots": 37,
      "matches": 0,
      "damage": 8625
    },
    "1552780800": {
      "kills": 75,
      "headshots": 197,
      "matches": 0,
      "damage": 42352
    },
    "1552867200": {
      "kills": 54,
      "headshots": 71,
      "matches": 0,
      "damage": 20745
    },
    "1553644800": {
      "kills": 15,
      "headshots": 46,
      "matches": 0,
      "damage": 6721
    },
    "1553990400": {
      "kills": 33,
      "headshots": 57,
      "matches": 0,
      "damage": 11742
    }
  }
}
```

So you can see that there arw some updated info after the apextab website search

**Comment by dpedoneze** [comment]
utime before and after:

1553961655 03/30/2019 @ 4:00pm (UTC)

1553982926 - 03/30/2019 @ 9:55pm (UTC)

**Comment by dpedoneze** [comment]
related https://github.com/Tabwire/ApexTab-API/issues/10

**Comment by BrendanMahoney** [comment]
Same issue here, refreshing player stats via the API does not work. Searching for players directly on apextab.com seems to be the only way to get the stats to update.

**Comment by Tabwire** [comment]
We're adding an extra GET var to force update the profile. Give us few hours and it will be ready.

**Comment by ajay340** [comment]
> We're adding an extra GET var to force update the profile. Give us few hours and it will be ready.

Any update on the force update?

**Comment by standerksen** [comment]
Wondering the same. Something I'm currently developing is dependant on this update.

**Comment by BrendanMahoney** [comment]
If it helps anyone, this is the current workaround I am using (Android):

    private WebView webView;

    private void refreshStats() {

        webView = new WebView(this);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.setWebViewClient(new WebViewClient() {
            public void onPageFinished(WebView view, String url) {
                new Handler().postDelayed(new Runnable() {
                    public void run() {
                        webView.loadUrl("javascript:(function(){" +
                                "l=document.getElementsByClassName('far fa-sync-alt cursor refreshplayer')[0];" +
                                "e=document.createEvent('HTMLEvents');" +
                                "e.initEvent('click',true,true);" +
                                "l.dispatchEvent(e);" +
                                "})()");
                        new Handler().postDelayed(new Runnable() {
                            public void run() {
                                webView.destroy();
                                webView = null;
                                getAccountStats();
                            }
                        }, 1000);
                    }
                }, 1000);
            }
        });
        webView.loadUrl("https://apextab.com/" + account.getAid());

    }

This opens the user's ApexTab profile page, programmatically clicks on the refresh button once loaded, and then calls your "get stats" method. Users don't see any of this, works for now at least!

**Comment by dpedoneze** [comment]
@BrendanMahoney I'm doing something like that to "force update" de status before getting it using the api.

Actually if you only get the search url (https://apextab.com/search-UserName) it updates the player status.

@Tabwire any news?

**Comment by BrendanMahoney** [comment]
@dpedoneze I noticed that too, the only problem I noticed is you can't specify the console that way

**Comment by standerksen** [comment]
@BrendanMahoney You can. Just fetch the `aid` from the regular API call, then do a GET request to https://apextab.com/ `aid` . Your Apex ID is specific to your console.

**Comment by ajay340** [comment]
> @BrendanMahoney You can. Just fetch the `aid` from the regular API call, then do a GET request to https://apextab.com/ `aid` . Your Apex ID is specific to your console.

I tried this, but it doesn't work update the stats.

**Comment by standerksen** [comment]
Aw, too bad. Let's hope @Tabwire has any updates for us.

**Comment by dpedoneze** [comment]
> @BrendanMahoney You can. Just fetch the `aid` from the regular API call, then do a GET request to https://apextab.com/ `aid` . Your Apex ID is specific to your console.

It didn't seems to be working now :(

**Comment by BrendanMahoney** [comment]
> > @BrendanMahoney You can. Just fetch the `aid` from the regular API call, then do a GET request to https://apextab.com/ `aid` . Your Apex ID is specific to your console.
> 
> It didn't seems to be working now :(

This doesn't work, you have to hit the refresh button that is on their profile as far as I know, just opening their profile URL isn't enough.

I just published v1 of my app if you wanna test the method yourself, I can only test on PC but it should work for all consoles: https://play.google.com/store/apps/details?id=com.mahoneytech.apexcompanion

**Comment by dpedoneze** [comment]
> @BrendanMahoney You can. Just fetch the `aid` from the regular API call, then do a GET request to https://apextab.com/ `aid` . Your Apex ID is specific to your console.

Just saw an update @ the website, it uses the https://apextab.com/mainpage.php?page=AID&updatenow=true 

If I'm not mistaken the `updatenow=true` flag wasn't there before :)

Since @Tabwire said that the api makes the same request, maybe we can use the same flag when getting the api endpoint :)

**Comment by dpedoneze** [comment]
Just tested using `updatenow=true` (https://apextab.com/api/player.php?aid=AID&updatenow=true) and it worked as expected (updated stats!)

**Comment by BrendanMahoney** [comment]
@dpedoneze 

Nice find, this speeds things up! Have you found a way to return JSON using this method yet?

**Comment by dpedoneze** [comment]
> @dpedoneze
> 
> Nice find, this speeds things up! Have you found a way to return JSON using this method yet?

[This one](https://apextab.com/api/player.php?aid=3983fe400d9872673fb66f7a6c27f67e&updatenow=true) returns JSON. The [other one]( https://apextab.com/mainpage.php?page=3983fe400d9872673fb66f7a6c27f67e&updatenow=true) would be used as a workaround by getting it and then getting the API endpint :)

**Comment by standerksen** [comment]
> If I'm not mistaken the `updatenow=true` flag wasn't there before :)

It was.

**Comment by ajay340** [comment]
> Just tested using `updatenow=true` (https://apextab.com/api/player.php?aid=AID&updatenow=true) and it worked as expected (updated stats!)

Just tested this with updatenow=true and my stats still did not update until I went on the mainpage.

**Comment by standerksen** [comment]
Can't you just perform a GET request to https://apextab.com/mainpage.php?page=AID&updatenow=true and then do whatever API call you wanted to do after that?

**Comment by ajay340** [comment]
Is anyone else experience their stats not updating, even on apextab.com?

**Comment by hadouken111** [comment]
@ajay340 Effectively the data of apextab.com, its also incorrect, I Compare my stats with https://apex.tracker.gg/ and apextracker display the real updating users stats.
do you think that this problem of erroneous data will be quickly corrected?
Thank
