### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by AKON825** [Tabwire/ApexTab-API#16]
Hi there thanks for reading this title!
I'm try to find official apex stat api but ea doesn't release yet
i'm so curious about where's this api data come from
Maybe it's so complicated to explain about that
But i'll be extremely grateful if you'd like to talking about that

**Comment by standerksen** [comment]
You can find certain endpoints when tapping traffic from the game using WireShark or other applications. Unfortunately, most people who found them aren't willing to share them. Links are also getting removed from the official EA forum.

**Comment by AKON825** [comment]
so des ga!
Your answer is very helpful. thanks for sharing imformation!
