### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by hadouken111** [Tabwire/ApexTab-API#17]
Hello, do you think that the problem of data not updated will be quickly corrected? It seems that no one is giving news of the advancement of the API.
Is the API being corrected?

**Comment by standerksen** [comment]
I have already given up on this one. Tons of better APIs out there.

**Comment by hadouken111** [comment]
Thank you for your answer, do you have an api to advise me?

**Comment by standerksen** [comment]
I am using the API by mozambique.re
https://github.com/HugoDerave/ApexLegendsAPI

**Comment by hadouken111** [comment]
Thank you so much bro  tried this API and it works: D

**Comment by Tabwire** [comment]
We were really busy with other projects like R6Tab updates. We fixed the API and now it's available to use error-free.
