### ISSUE TITLE
Search: doesn't find all players

### ISSUE THREAD

**Issue by ghost** [Tabwire/ApexTab-API#3]
I'm playing from Europe on PS4 as `fibric-` but the search didn't show a result for `fibric`. I guess your API is bound to a specific region and doesn't cover all regions.

**Comment by AustinLeath** [comment]
What was the exact call you were using? @fibric

**Comment by echofriendly** [comment]
https://apextab.com/api/search.php?platform=pc&search=echo

there is more than 1 account with the word echo in it for example mine is echofriendlyx
this doesn't seem to work at all, i tried every account in a discord with 100s of people and it found none of them.

**Comment by AustinLeath** [comment]
@echofriendly @fibric We are working on it currently.

**Comment by AustinLeath** [comment]
Okay @echofriendly @fibric you guys have to add the account to the apextab database first then make your query. you can curl the api like this: `curl https://apextab.com/api/search.php?platform=pc\&search=echo` make sure that you put the backslash before `&search=` like this: `\&search=echo` . Please note that it works if you just click the link in a web browser like in chrome or safari or whatever, but if you are using `wget` or `curl` you will need to add the back slash.

Also: @fibric , you need to set your kills in one of your trackers on the actual apex legends game which will enable you to be tracked by our database. As it stands, the user `fibric-` on psn is not tracked because `Please set the kills as a tracker then try again.`. That is the message I get when i try to search you up.

**Comment by ghost** [comment]
@AustinLeath I used this URL
`https://apextab.com/api/search.php?platform=psn&search=fibric`

totalresults | 0
-- | --


and this URL `https://apextab.com/api/search.php?platform=psn&search=fibric-`

totalresults | 0
-- | --

Here is the quick and dirty code I use.
```javascript
(function(callback) {
    'use strict';
        
    const httpTransport = require('https');
    const responseEncoding = 'utf8';
    const httpOptions = {
        hostname: 'apextab.com',
        port: '443',
        path: '/api/search.php?platform=psn&search=fibric',
        method: 'GET',
        headers: {}
    };
    httpOptions.headers['User-Agent'] = 'node ' + process.version;
 
    const request = httpTransport.request(httpOptions, (res) => {
        let responseBufs = [];
        let responseStr = '';
        
        res.on('data', (chunk) => {
            if (Buffer.isBuffer(chunk)) {
                responseBufs.push(chunk);
            }
            else {
                responseStr = responseStr + chunk;            
            }
        }).on('end', () => {
            responseStr = responseBufs.length > 0 ? 
                Buffer.concat(responseBufs).toString(responseEncoding) : responseStr;
            
            callback(null, res.statusCode, res.headers, responseStr);
        });
        
    })
    .setTimeout(0)
    .on('error', (error) => {
        callback(error);
    });
    request.write("")
    request.end();
    

})((error, statusCode, headers, body) => {
    console.log('ERROR:', error); 
    console.log('STATUS:', statusCode);
    console.log('HEADERS:', JSON.stringify(headers));
    console.log('BODY:', body);
});
```

**Comment by ghost** [comment]
Okay, so the API response is just misleading.

**Comment by AustinLeath** [comment]
> @AustinLeath I used this URL
> `https://apextab.com/api/search.php?platform=psn&search=fibric`
> 
> totalresults	0
> and this URL `https://apextab.com/api/search.php?platform=psn&search=fibric-`
> 
> totalresults	0
> Here is the quick and dirty code I use.
> 
> ```js
> (function(callback) {
>     'use strict';
>         
>     const httpTransport = require('https');
>     const responseEncoding = 'utf8';
>     const httpOptions = {
>         hostname: 'apextab.com',
>         port: '443',
>         path: '/api/search.php?platform=psn&search=fibric',
>         method: 'GET',
>         headers: {}
>     };
>     httpOptions.headers['User-Agent'] = 'node ' + process.version;
>  
>     const request = httpTransport.request(httpOptions, (res) => {
>         let responseBufs = [];
>         let responseStr = '';
>         
>         res.on('data', (chunk) => {
>             if (Buffer.isBuffer(chunk)) {
>                 responseBufs.push(chunk);
>             }
>             else {
>                 responseStr = responseStr + chunk;            
>             }
>         }).on('end', () => {
>             responseStr = responseBufs.length > 0 ? 
>                 Buffer.concat(responseBufs).toString(responseEncoding) : responseStr;
>             
>             callback(null, res.statusCode, res.headers, responseStr);
>         });
>         
>     })
>     .setTimeout(0)
>     .on('error', (error) => {
>         callback(error);
>     });
>     request.write("")
>     request.end();
>     
> 
> })((error, statusCode, headers, body) => {
>     console.log('ERROR:', error); 
>     console.log('STATUS:', statusCode);
>     console.log('HEADERS:', JSON.stringify(headers));
>     console.log('BODY:', body);
> });
> ```

Try using a user that is already in the database. As I said before, the user MUST be in the database in order for the api to find them.

**Comment by ghost** [comment]
Yes, I understand, that's why also put `Okay, so the API response is just misleading.`
There is a distinct difference between the user profile does not exist in your database, and the user profile does not fulfill your requirements to be stored in the database.
In both cases the result 0 is correct, but the missing reason leads to threads like this.

**Comment by AustinLeath** [comment]
> 
> 
> Yes, I understand, that's why also put `Okay, so the API response is just misleading.`
> There is a distinct difference between the user profile does not exist in your database, and the user profile does not fulfill your requirements to be stored in the database.
> In both cases the result 0 is correct, but the missing reason leads to threads like this.

Oh, I didn't even see the post where you said the response is misleading, sorry about that. Anyways, did this sort the issue for you?

**Comment by AustinLeath** [comment]
Marked as closed.
