### ISSUE TITLE
No Games played statistic!

### ISSUE THREAD

**Issue by AlfiePerkins123** [Tabwire/ApexTab-API#5]
There are no games played on this! Not sure if this is possible, if not is their an ETA?

**Comment by AustinLeath** [comment]
We are working on providing more statistics @AlfiePerkins123

**Comment by alfiejfs** [comment]
@AustinLeath @Tabwire I know this isn't on topic to the issue, but how are you getting the stats?

**Comment by Tabwire** [comment]
We cannot provide the endpoints without Respawn's permission. You can try to find it online.

**Comment by Tabwire** [comment]
> There are no games played on this! Not sure if this is possible, if not is their an ETA?

There is gameplayed, we call it "Matches".

**Comment by AustinLeath** [comment]
Marking as closed.
