### ISSUE TITLE
Search: add multi platform search

### ISSUE THREAD

**Issue by ghost** [Tabwire/ApexTab-API#6]
I just tried to find players on all platforms by leaving out the platform param.
`https://apextab.com/api/search.php?&search=ball`

totalresults | 0
-- | --

I tried to use multi param values.
`https://apextab.com/api/search.php?platform=pc,psn&search=ball`

totalresults | 0
-- | --

I could run three individual queries for each platform one query and merge the responses, but since GraphQL we all know the fastest apps issue exactly one query to fetch all the data needed to render the UI.

**Comment by AustinLeath** [comment]
@Tabwire

**Comment by AustinLeath** [comment]
We are looking into this, it is not a priority at the moment.
