### ISSUE TITLE
Not an issue. Just a heads up!

### ISSUE THREAD

**Issue by JaydenMaalouf** [Tabwire/ApexTab-API#7]
Hey,
Saw your API today and thought this thing would need a wrapper made for it... so I've gone ahead and made a small little C# Wrapper so people can easily use it within their projects just by using the NuGet Package. See here: https://github.com/JaydenMaalouf/ApexAPI

If theres anything you would like me to add or remove, let me know!
Feel free to get in touch with me via Discord (Kanga#8041) <3

Cheers,
Kanga

**Comment by AustinLeath** [comment]
Nice! I love this, I am pretty sure we may be optimizing this API in the next few weeks so just know it may break a feature or two.

**Comment by JaydenMaalouf** [comment]
No problemo! Happy to keep support for this. Just keep me informed via Discord and I'll fix it up :p
